language: ruby
before_install:
- gem install bundler
- gem install kramdown
- gem install therubyracer
- gem install s3_website
- gem install jekyll
- gem install jekyll-less
- gem install jekyll-sitemap
- gem install jekyll-press
- export S3_CREDENTIALS="${S3_ACCESS_KEY_ID}:${S3_SECRET_KEY}"
script: jekyll build -d _site
after_success: travis_retry s3_website push
rvm:
- 2.1.1
env:
  global:
  - S3_REGION: us-east-1
  - S3_BUCKET_NAME: barkspy
  - secure: 2PCzB2DiMh0wkE3ax4pJxCLQdYtFfMUZLg8jVWi9Di8MB1BJMDoEJ/c0hCPA+SLN9pObLKsXudTJucyzDRc+k8eYiOW7rfHAzen0so+77KSJWUpLvBMDaUf9I/RPysCpeoGnwmqmRhKCAP4MB1yu/mMm7/vnRtcHq1dq3heaD5E=
  - secure: dt649reD2myIrRJIYEzLddtB0beHBYJHqlzmH8YbDIHhwYGIyGkiRu0dMSJFWAXgxBSrobdXJtTg12OfKJ2OqSMsa3XkaELw67tmjCzTpdCraz5nyyUeD09+VhH+u5uXCXzx2YSNcQEiqy3UiCKEC+8KeQlFwDV+dS6Df/lGQQo=
