language: ruby
before_install:
- gem install bundler
- gem install kramdown
- gem install therubyracer
- gem install s3_website
- gem install jekyll
- gem install jekyll-less
- gem install jekyll-sitemap
- export S3_CREDENTIALS="${S3_ACCESS_KEY_ID}:${S3_SECRET_KEY}"
script: jekyll build -d _site
after_success: travis_retry s3_website push
rvm:
- 2.1.1
env:
  global:
  - S3_REGION: us-east-1
  - S3_BUCKET_NAME: barkspy
deploy:
  provider: s3
  access_key_id: AKIAI7RRWEDYXXMYXK4A
  secret_access_key:
    secure: itRD152Kwhv5K9Qvzi2INn7fMFWa32h/JGUllsN1MWTraMGxWO7nn9Aim/FVak4jT9I6irzcyZ8Eh3a1DxP/jiYqyU7ur7ELSgf/Ofdakz8lRb+0Uwf4C/2jsdi+HY2WcrkeJt7ngJKQ/dqnTIKiEw4gblfpczHgD0oWrMjFsug=
  bucket: barkspy
  acl: public_read
  on:
    repo: mattrude/barkspy
    branch: jekyll-lists
