language: ruby
before_install:
- gem install bundler
- gem install kramdown
- gem install therubyracer
- gem install s3_website
- gem install jekyll
- gem install jekyll-less
- gem install jekyll-sitemap
- gem install jekyll-press
- export S3_CREDENTIALS="${S3_ACCESS_KEY_ID}:${S3_SECRET_KEY}"
script: jekyll build -d _site
after_success: travis_retry s3_website push
rvm:
- 2.1.1
env:
  global:
  - S3_REGION: us-east-1
  - S3_BUCKET_NAME: barkspy
  - secure: x90XoWFbpxEsfxzfULNwjTcg5q4WkZyF3s39KZJOJZ2gbqwEYlvmYduUWdvzrwPA8Y5Y4vNqNV6jAw+OyrpslTE2YXjUjPSAeP04ouufzdAZNN7AnyRXEV5EnUdwKLEe0nXHugIeYyMrH4GfttcAnU/ok35L+PutU+0x5aKi3bw=
  - secure: 1wtUBmv/dUqtM7AFN77Av8YUyOoo5ezQZmd1n+GJEZTD7B8liML+CS+bdQeChrD8CWCUn9VfV2HYcMYInDg32iqL0YoU+8Fd6i5OmRnyOIGeWX6uPQ5gJHTc+6l85/IIkTGQeLPnUdb2sa4CJ9eBTXQxol94CrxqRSlYcDnq1DU=
